name: RcDamageCore
version: '${version}'
main: net.azisaba.rcdamagecore.RcDamageCore
api-version: '1.21'
authors:
  - takumi3s
  - sysnote8
depend:
  - MythicMobs
  - LoreEditor
commands:
  testcmd:
    permisison: rcdamagecore.cmd.testcmd
permissions:
  rcdamagecore.cmd.testcmd:
    default: op