name: RcDamageCore
version: '${project.version}'
main: takumi3s.rcdamagecore.RcDamageCore
api-version: '1.21'
authors:
  - takumi3s
  - sysnote8
depend:
  - ProtocolLib
  - MythicMobs
commands:
  testcmd:
    permisison: rcdamagecore.cmd.testcmd
permissions:
  rcdamagecore.cmd.testcmd:
    default: op